SELECT * FROM PRODUCT_LOT WHERE ITEM_NO='AHP-N01'

SELECT COUNT(*) FROM PRODUCT_LOT WHERE LQTY =0

SELECT * FROM PRODUCT_LOT WHERE LQTY =0


SELECT * FROM STOCKTRANS WHERE ITEM_NO='AHP-H01'

SELECT L.ITEM_NO AS ITEM_NO,L.LOT_NO,LOT_EXP,WH_NO,L.BIN_NO,
(SELECT TOP 1 G.GRN_NO 
FROM GRNDSCRP G INNER JOIN GRNLQTY Y ON G.GRN_NO=Y.GRN_NO AND G.SEQ_NO=Y.SEQ_NO AND G.SUBSEQ_NO=Y.SUBSEQ_NO 
WHERE Y.LOT_NO=L.LOT_NO AND G.ITEM_NO=L.ITEM_NO ORDER BY G.RECDATE DESC,G.GRN_NO,G.LINE_NO) AS GRN_NO,
(SELECT MIN(G.RECDATE) 
FROM GRNDSCRP G INNER JOIN GRNLQTY Y ON G.GRN_NO=Y.GRN_NO AND G.SEQ_NO=Y.SEQ_NO AND G.SUBSEQ_NO=Y.SUBSEQ_NO 
WHERE Y.LOT_NO=L.LOT_NO AND G.ITEM_NO=L.ITEM_NO) AS RECDATE,
(SELECT SUM(LQTY-LSHIP_QTY) 
FROM (INVLQTY Y INNER JOIN INVDSCRP D ON D.INV_NO=Y.INV_NO AND D.SEQ_NO=Y.SEQ_NO AND D.SUBSEQ_NO=Y.SUBSEQ_NO) INNER JOIN INVOICE H ON Y.INV_NO=H.INV_NO 
WHERE Y.LOT_NO=L.LOT_NO AND D.ITEM_NO=L.ITEM_NO AND SHIPCOMPLETE=0 AND LQTY>LSHIP_QTY AND H.STATUS IN ('D','E')) AS HOLDQTY,
(SELECT SUM(Y.LQTY*Y.UNIT_RATIO) 
FROM GRNDSCRP G INNER JOIN GRNLQTY Y ON G.GRN_NO=Y.GRN_NO AND G.SEQ_NO=Y.SEQ_NO AND G.SUBSEQ_NO=Y.SUBSEQ_NO 
WHERE Y.LOT_NO=L.LOT_NO AND G.ITEM_NO=L.ITEM_NO) AS GQTY,LQTY,UNIT,UNIT_RATIO,LQTY*UNIT_RATIO,L.COST 
FROM PRODUCT_LOT L WHERE L.ITEM_NO='AHP-N02'

SELECT * FROM GRNLQTY WHERE GRN_NO IN ('01','20180504TMZ') AND LOT_NO='20190501-5F70347'
SELECT * FROM GRNDSCRP WHERE ITEM_NO='Z-YMT-N12'

SELECT * FROM PRODUCT_LOT WHERE ITEM_NO='Z-YMT-N12'

SELECT SUM(Y.LQTY*Y.UNIT_RATIO)AS TQTY,G.QTY,Y.LQTY,Y.LOT_NO,G.GRN_NO
FROM GRNDSCRP G INNER JOIN GRNLQTY Y ON G.GRN_NO=Y.GRN_NO AND G.SEQ_NO=Y.SEQ_NO AND G.SUBSEQ_NO=Y.SUBSEQ_NO 
WHERE G.ITEM_NO='AHP-N02' GROUP BY G.QTY,Y.LQTY ,Y.LOT_NO,G.GRN_NO

SELECT * FROM INVOICE

 